var path = require("path");
var appDir = path.dirname(require.main.filename);

const WATCHEDSETCODESDIRECTORY = appDir + "/data";
const WATCHEDSETCODESFILENAME = "watchedsetcodes.json";
const WATCHEDSETCODESPATH =
  WATCHEDSETCODESDIRECTORY + "/" + WATCHEDSETCODESFILENAME;

module.exports = {
  BOTPREFIX: "!",
  BOTNECESSARYPERMISSION: "MANAGE_MESSAGES",
  SPOILERWATCHINTERVALTIME: 1000 * 60 * 30, // in milliseconds, so 1000 * 60 * 30 = every 30 minutes
  WATCHEDSETCODESDIRECTORY: WATCHEDSETCODESDIRECTORY,
  WATCHEDSETCODESFILENAME: WATCHEDSETCODESFILENAME,
  WATCHEDSETCODESPATH: WATCHEDSETCODESPATH,
};
